name: appvisor_flutter_sdk
description: "A push notification plugin for Flutter."
version: 1.1.0
homepage:

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: biz.appvisor.appvisor_flutter_sdk
        pluginClass: AppvisorFlutterSdkPlugin
      ios:
        pluginClass: AppvisorFlutterSdkPlugin
      # web:
      #   pluginClass: AppvisorFlutterSdkWeb
      #   fileName: appvisor_flutter_sdk_web.dart